version: '3.20'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 9001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  haproxy:
    image: haproxy:alpine
    ports:
      - 9002:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  traefik:
    # no alpine tag
    image: traefik:latest
    command: 
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 9004:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  caddy:
    image: caddy:latest
    ports:
      - 9005:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  apache:
    image: httpd:latest
    environment:
      - APACHE_LOG_DIR=/usr/local/apache2/logs
    ports:
      - 9006:80
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
  backend:
    build: backend
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/`)"